reddit:
  client_id: "YOUR_CLIENT_ID"
  client_secret: "YOUR_CLIENT_SECRET"
  user_agent: "SentimentAnalyzer/1.0"
  subreddits: ["wallstreetbets"]

twitter:
  api_key: "YOUR_API_KEY"
  api_secret: "YOUR_API_SECRET"
  access_token: "YOUR_ACCESS_TOKEN"
  access_token_secret: "YOUR_ACCESS_TOKEN_SECRET"

stocks:
  symbols: ["GME", "AMC", "TSLA"]
  timeframe: "1d"
  period: "1mo"